### PR TITLE
Add -Xdoclint for javadoc plugin

### PR DESCRIPTION
**Pull request by ahousing**

### CODE REVIEW

**Comment by dpwspoon** [comment]
Why did you add this?

**Comment by ahousing** [comment]
May need to redo [adding json files](https://github.com/kaazing/staging-bower-enterprise.javascript.client/pull/1).  And all of this is for [D plans](https://github.com/kaazing/roadmap/issues/729)

**Comment by ahousing** [comment]
[Build failed](http://jenkins.kaazing.wan/view/release_build/job/bower-maven-plugin-ABC-release/4/console).  I was under the impression this is how you fixed this issue.

**Comment by dpwspoon** [comment]
Sounds good.  I thought you might have been looking into the travis ci failure

**Pull request merged**
